// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.slezacek.etnetera.discount.model;

import cz.slezacek.etnetera.discount.model.CodeDataOnDemand;
import cz.slezacek.etnetera.discount.model.CodeIntegrationTest;
import cz.slezacek.etnetera.discount.service.CodeService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CodeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CodeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CodeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CodeIntegrationTest: @Transactional;
    
    @Autowired
    CodeDataOnDemand CodeIntegrationTest.dod;
    
    @Autowired
    CodeService CodeIntegrationTest.codeService;
    
    @Test
    public void CodeIntegrationTest.testCountAllCodes() {
        Assert.assertNotNull("Data on demand for 'Code' failed to initialize correctly", dod.getRandomCode());
        long count = codeService.countAllCodes();
        Assert.assertTrue("Counter for 'Code' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CodeIntegrationTest.testFindCode() {
        Code obj = dod.getRandomCode();
        Assert.assertNotNull("Data on demand for 'Code' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Code' failed to provide an identifier", id);
        obj = codeService.findCode(id);
        Assert.assertNotNull("Find method for 'Code' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Code' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CodeIntegrationTest.testFindAllCodes() {
        Assert.assertNotNull("Data on demand for 'Code' failed to initialize correctly", dod.getRandomCode());
        long count = codeService.countAllCodes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Code', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Code> result = codeService.findAllCodes();
        Assert.assertNotNull("Find all method for 'Code' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Code' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CodeIntegrationTest.testFindCodeEntries() {
        Assert.assertNotNull("Data on demand for 'Code' failed to initialize correctly", dod.getRandomCode());
        long count = codeService.countAllCodes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Code> result = codeService.findCodeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Code' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Code' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CodeIntegrationTest.testFlush() {
        Code obj = dod.getRandomCode();
        Assert.assertNotNull("Data on demand for 'Code' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Code' failed to provide an identifier", id);
        obj = codeService.findCode(id);
        Assert.assertNotNull("Find method for 'Code' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCode(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Code' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CodeIntegrationTest.testUpdateCodeUpdate() {
        Code obj = dod.getRandomCode();
        Assert.assertNotNull("Data on demand for 'Code' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Code' failed to provide an identifier", id);
        obj = codeService.findCode(id);
        boolean modified =  dod.modifyCode(obj);
        Integer currentVersion = obj.getVersion();
        Code merged = codeService.updateCode(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Code' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CodeIntegrationTest.testSaveCode() {
        Assert.assertNotNull("Data on demand for 'Code' failed to initialize correctly", dod.getRandomCode());
        Code obj = dod.getNewTransientCode(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Code' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Code' identifier to be null", obj.getId());
        try {
            codeService.saveCode(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Code' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CodeIntegrationTest.testDeleteCode() {
        Code obj = dod.getRandomCode();
        Assert.assertNotNull("Data on demand for 'Code' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Code' failed to provide an identifier", id);
        obj = codeService.findCode(id);
        codeService.deleteCode(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'Code' with identifier '" + id + "'", codeService.findCode(id));
    }
    
}
