// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.slezacek.etnetera.discount.model;

import cz.slezacek.etnetera.discount.model.PhonenumberIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PhonenumberIntegrationTest_Roo_Configurable {
    
    declare @type: PhonenumberIntegrationTest: @Configurable;
    
}
